project 'CCCUIKit.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'CCCUIKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  platform :ios, '8.0'

  # Pods for CCCUIKit
  pod 'CCCUIKit', :path => '../'

end
